In [1]:
import pandas as pd

In [5]:
snsdata = pd.read_csv('d:/data/snsdata.csv')
snsdata.shape

(30000, 40)

In [31]:
snsdata.gender.value_counts(normalize=False,sort=True,ascending=True,dropna=False)

gender
M     5222
F    24778
Name: count, dtype: int64

In [29]:
snsdata.isna().sum()

gradyear           0
gender             0
age             5087
friends            0
basketball         0
football           0
soccer             0
softball           0
volleyball         0
swimming           0
cheerleading       0
baseball           0
tennis             0
sports             0
cute               0
sex                0
sexy               0
hot                0
kissed             0
dance              0
band               0
marching           0
music              0
rock               0
god                0
church             0
jesus              0
bible              0
hair               0
dress              0
blonde             0
mall               0
shopping           0
clothes            0
hollister          0
abercrombie        0
die                0
death              0
drunk              0
drugs              0
dtype: int64

In [27]:
snsdata.gender.fillna(value='F',inplace=True)

In [33]:
snsdata = pd.read_csv('d:/data/snsdata.csv')
snsdata.shape

(30000, 40)

In [37]:
snsdata.head(10)

,gradyear,gender,age,friends,basketball,football,soccer,softball,volleyball,swimming,...,blonde,mall,shopping,clothes,hollister,abercrombie,die,death,drunk,drugs
0,2006,M,NaN,7,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2006,F,18.801,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,2006,M,18.335,69,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,2006,F,18.875,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2006,NaN,18.995,10,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,1,1
5,2006,F,NaN,142,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
6,2006,F,18.930,72,0,0,0,0,0,0,...,0,2,0,0,2,0,0,0,0,0
7,2006,M,18.322,17,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,2006,F,19.055,52,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,2006,F,18.708,39,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [39]:
snsdata.age.isna().sum()

5087

In [43]:
snsdata.age.fillna(method='ffill')

C:\Users\Vamsi Krishna\AppData\Local\Temp\ipykernel_21460\2365355134.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  snsdata.age.fillna(method='ffill')

0           NaN
1        18.801
2        18.335
3        18.875
4        18.995
          ...
29995    16.115
29996    15.792
29997    15.784
29998    16.378
29999    18.724
Name: age, Length: 30000, dtype: float64

In [47]:
snsdata.age.bfill(inplace=True)

In [51]:
snsdata.head(10)

,gradyear,gender,age,friends,basketball,football,soccer,softball,volleyball,swimming,...,blonde,mall,shopping,clothes,hollister,abercrombie,die,death,drunk,drugs
0,2006,M,18.801,7,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2006,F,18.801,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,2006,M,18.335,69,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,2006,F,18.875,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2006,NaN,18.995,10,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,1,1
5,2006,F,18.930,142,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
6,2006,F,18.930,72,0,0,0,0,0,0,...,0,2,0,0,2,0,0,0,0,0
7,2006,M,18.322,17,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,2006,F,19.055,52,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,2006,F,18.708,39,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [57]:
snsdata.gender.ffill(inplace=True)

In [59]:
snsdata.isna().sum()

gradyear        0
gender          0
age             0
friends         0
basketball      0
football        0
soccer          0
softball        0
volleyball      0
swimming        0
cheerleading    0
baseball        0
tennis          0
sports          0
cute            0
sex             0
sexy            0
hot             0
kissed          0
dance           0
band            0
marching        0
music           0
rock            0
god             0
church          0
jesus           0
bible           0
hair            0
dress           0
blonde          0
mall            0
shopping        0
clothes         0
hollister       0
abercrombie     0
die             0
death           0
drunk           0
drugs           0
dtype: int64

In [77]:
snsdata = pd.read_csv('d:/data/snsdata.csv')
snsdata.shape

(30000, 40)

In [79]:
snsdata.age.isna().sum()

5087

In [81]:
snsdata.age.mean()

17.993909886404687

In [83]:
snsdata.age.ffill().mean()

17.958869262308742

In [87]:
snsdata.age.bfill().mean()

18.021936866666664

In [89]:
snsdata.age.fillna(value=snsdata.age.mean(),inplace=True)

In [91]:
snsdata.age.isna().sum()

0

In [93]:
snsdata.age.mean()

17.993909886404687

In [ ]:
snsdata.ffill(