In [1]:
import pandas as pd

In [3]:
emp = pd.read_csv('d:/NewData/employees1.csv')
emp

   empno ename   sal  deptno
0   1001  abcd  2500      30
1   1002   xyz  1500      20
2   1003  wxyz  2400      10
3   1004  pqrs  1200      20
4   1005  efgh  3000      50

In [5]:
dept = pd.read_csv('d:/NewData/department.csv')
dept

   deptno       dname   location
0      10    accounts  hyderabad
1      20       sales    chennai
2      30  production     mumbai
3      40    research      delhi

In [23]:
inner_join= pd.merge(left=emp,right=dept,how='inner',on='deptno',indicator="status")
inner_join

   empno ename   sal  deptno       dname   location status
0   1001  abcd  2500      30  production     mumbai   both
1   1002   xyz  1500      20       sales    chennai   both
2   1003  wxyz  2400      10    accounts  hyderabad   both
3   1004  pqrs  1200      20       sales    chennai   both

In [25]:
left_outer_join= pd.merge(left=emp,right=dept,how='left',on='deptno',indicator="status")
left_outer_join

   empno ename   sal  deptno       dname   location     status
0   1001  abcd  2500      30  production     mumbai       both
1   1002   xyz  1500      20       sales    chennai       both
2   1003  wxyz  2400      10    accounts  hyderabad       both
3   1004  pqrs  1200      20       sales    chennai       both
4   1005  efgh  3000      50         NaN        NaN  left_only

In [27]:
right_outer_join= pd.merge(left=emp,right=dept,how='right',on='deptno',indicator="status")
right_outer_join

    empno ename     sal  deptno       dname   location      status
0  1003.0  wxyz  2400.0      10    accounts  hyderabad        both
1  1002.0   xyz  1500.0      20       sales    chennai        both
2  1004.0  pqrs  1200.0      20       sales    chennai        both
3  1001.0  abcd  2500.0      30  production     mumbai        both
4     NaN   NaN     NaN      40    research      delhi  right_only

In [29]:
full_outer_join= pd.merge(left=emp,right=dept,how='outer',on='deptno',indicator="status")
full_outer_join

    empno ename     sal  deptno       dname   location      status
0  1003.0  wxyz  2400.0      10    accounts  hyderabad        both
1  1002.0   xyz  1500.0      20       sales    chennai        both
2  1004.0  pqrs  1200.0      20       sales    chennai        both
3  1001.0  abcd  2500.0      30  production     mumbai        both
4     NaN   NaN     NaN      40    research      delhi  right_only
5  1005.0  efgh  3000.0      50         NaN        NaN   left_only

In [33]:
emp1 = pd.read_csv('d:/NewData/employees1.csv')
emp1

   empno ename   sal  deptno
0   1001  abcd  2500      30
1   1002   xyz  1500      20
2   1003  wxyz  2400      10
3   1004  pqrs  1200      20
4   1005  efgh  3000      50

In [39]:
dept1 = pd.read_csv('d:/NewData/dept.txt',sep="\t")
dept1

   dno       dname       loc
0   10    accounts  new york
1   20       sales    boston
2   30  operations   chicago
3   40    research    dallas

In [45]:
pd.merge(left=emp1,right=dept1,left_on="deptno",right_on="dno",how='inner',indicator='status')

   empno ename   sal  deptno  dno       dname       loc status
0   1001  abcd  2500      30   30  operations   chicago   both
1   1002   xyz  1500      20   20       sales    boston   both
2   1003  wxyz  2400      10   10    accounts  new york   both
3   1004  pqrs  1200      20   20       sales    boston   both

In [47]:
pd.merge(left=emp1,right=dept1,left_on="deptno",right_on="dno",how='left',indicator='status')

   empno ename   sal  deptno   dno       dname       loc     status
0   1001  abcd  2500      30  30.0  operations   chicago       both
1   1002   xyz  1500      20  20.0       sales    boston       both
2   1003  wxyz  2400      10  10.0    accounts  new york       both
3   1004  pqrs  1200      20  20.0       sales    boston       both
4   1005  efgh  3000      50   NaN         NaN       NaN  left_only

In [49]:
pd.merge(left=emp1,right=dept1,left_on="deptno",right_on="dno",how='right',indicator='status')

    empno ename     sal  deptno  dno       dname       loc      status
0  1003.0  wxyz  2400.0    10.0   10    accounts  new york        both
1  1002.0   xyz  1500.0    20.0   20       sales    boston        both
2  1004.0  pqrs  1200.0    20.0   20       sales    boston        both
3  1001.0  abcd  2500.0    30.0   30  operations   chicago        both
4     NaN   NaN     NaN     NaN   40    research    dallas  right_only

In [51]:
pd.merge(left=emp1,right=dept1,left_on="deptno",right_on="dno",how='outer',indicator='status')

    empno ename     sal  deptno   dno       dname       loc      status
0  1003.0  wxyz  2400.0    10.0  10.0    accounts  new york        both
1  1002.0   xyz  1500.0    20.0  20.0       sales    boston        both
2  1004.0  pqrs  1200.0    20.0  20.0       sales    boston        both
3  1001.0  abcd  2500.0    30.0  30.0  operations   chicago        both
4     NaN   NaN     NaN     NaN  40.0    research    dallas  right_only
5  1005.0  efgh  3000.0    50.0   NaN         NaN       NaN   left_only

In [63]:
emp2 = pd.read_csv('d:/NewData/employees1.csv',index_col="deptno")
emp2

        empno ename   sal
deptno
30       1001  abcd  2500
20       1002   xyz  1500
10       1003  wxyz  2400
20       1004  pqrs  1200
50       1005  efgh  3000

In [65]:
dept2 = pd.read_csv('d:/NewData/dept.txt',sep="\t",index_col="dno")
dept2

          dname       loc
dno
10     accounts  new york
20        sales    boston
30   operations   chicago
40     research    dallas

In [67]:
pd.merge(left=emp2,right=dept2,left_index=True,right_index=True,how='inner',indicator='status')

        empno ename   sal       dname       loc status
deptno
30       1001  abcd  2500  operations   chicago   both
20       1002   xyz  1500       sales    boston   both
10       1003  wxyz  2400    accounts  new york   both
20       1004  pqrs  1200       sales    boston   both

In [69]:
pd.merge(left=emp2,right=dept2,left_index=True,right_index=True,how='left',indicator='status')

        empno ename   sal       dname       loc     status
deptno
30       1001  abcd  2500  operations   chicago       both
20       1002   xyz  1500       sales    boston       both
10       1003  wxyz  2400    accounts  new york       both
20       1004  pqrs  1200       sales    boston       both
50       1005  efgh  3000         NaN       NaN  left_only

In [71]:
pd.merge(left=emp2,right=dept2,left_index=True,right_index=True,how='right',indicator='status')

         empno ename     sal       dname       loc      status
deptno
10      1003.0  wxyz  2400.0    accounts  new york        both
20      1002.0   xyz  1500.0       sales    boston        both
20      1004.0  pqrs  1200.0       sales    boston        both
30      1001.0  abcd  2500.0  operations   chicago        both
40         NaN   NaN     NaN    research    dallas  right_only

In [73]:
pd.merge(left=emp2,right=dept2,left_index=True,right_index=True,how='outer',indicator='status')

         empno ename     sal       dname       loc      status
deptno
10      1003.0  wxyz  2400.0    accounts  new york        both
20      1002.0   xyz  1500.0       sales    boston        both
20      1004.0  pqrs  1200.0       sales    boston        both
30      1001.0  abcd  2500.0  operations   chicago        both
40         NaN   NaN     NaN    research    dallas  right_only
50      1005.0  efgh  3000.0         NaN       NaN   left_only

In [75]:
emp3 = pd.read_csv('d:/NewData/employees1.csv')
emp3

   empno ename   sal  deptno
0   1001  abcd  2500      30
1   1002   xyz  1500      20
2   1003  wxyz  2400      10
3   1004  pqrs  1200      20
4   1005  efgh  3000      50

In [77]:
dept3 = pd.read_csv('d:/NewData/department.csv')
dept3

   deptno       dname   location
0      10    accounts  hyderabad
1      20       sales    chennai
2      30  production     mumbai
3      40    research      delhi

In [89]:
pd.merge(left=emp3,right=dept3,on='deptno',how='inner',indicator='status',validate="many_to_one")

   empno ename   sal  deptno       dname   location status
0   1001  abcd  2500      30  production     mumbai   both
1   1002   xyz  1500      20       sales    chennai   both
2   1003  wxyz  2400      10    accounts  hyderabad   both
3   1004  pqrs  1200      20       sales    chennai   both

In [95]:
emp4 = pd.read_csv('d:/NewData/employees_new.txt')
emp4

   empno ename   sal  deptno   dname
0   1001  abcd  2500      30  junior
1   1002   xyz  1500      10  junior
2   1003  pqrs  2000      20  junior
3   1004  pppp  3000      50  senior
4   1005  efgh  2500      30  senior
5   1006   ywx  1400      10  senior
6   1007  mnop  1200      10  junior

In [97]:
dept4= pd.read_csv('d:/NewData/department.csv')
dept4

   deptno       dname   location
0      10    accounts  hyderabad
1      20       sales    chennai
2      30  production     mumbai
3      40    research      delhi

In [133]:
pd.merge(left=emp4,right=dept4,on='deptno',suffixes=("_emp","_dept"),sort=True,copy=True)

   empno ename   sal  deptno dname_emp  dname_dept   location
0   1002   xyz  1500      10    junior    accounts  hyderabad
1   1006   ywx  1400      10    senior    accounts  hyderabad
2   1007  mnop  1200      10    junior    accounts  hyderabad
3   1003  pqrs  2000      20    junior       sales    chennai
4   1001  abcd  2500      30    junior  production     mumbai
5   1005  efgh  2500      30    senior  production     mumbai