In [1]:
import pandas as pd

In [5]:
cars_sales = pd.read_csv('d:/data/cars/Car_sales_transactions.csv')
cars_sales.shape

(7906, 16)

In [7]:
cars_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7906 entries, 0 to 7905
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales_ID       7906 non-null   int64
 1   Name           7906 non-null   object
 2   Year           7906 non-null   int64
 3   Selling_Price  7906 non-null   int64
 4   km_Driven      7906 non-null   int64
 5   City_Code      7906 non-null   object
 6   State_Code     7906 non-null   object
 7   Postal_Code    7906 non-null   int64
 8   Fuel           7906 non-null   object
 9   Seller_Type    7906 non-null   object
 10  Transmission   7906 non-null   object
 11  Owner          7906 non-null   object
 12  Mileage        7906 non-null   object
 13  Engine         7906 non-null   object
 14  Max_Power      7906 non-null   object
 15  Seats          7906 non-null   int64
dtypes: int64(6), object(10)
memory usage: 988.4+ KB

In [9]:
cars_sales.head()

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code,Postal_Code,Fuel,Seller_Type,Transmission,Owner,Mileage,Engine,Max_Power,Seats
0,1,Maruti Swift Dzire VDI,2014,450000,145500,CT01,ST15,400001,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5
1,2,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,CT28,ST11,834001,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5
2,3,Honda City 2017-2020 EXi,2006,158000,140000,CT12,ST28,201301,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,5
3,4,Hyundai i20 Sportz Diesel,2010,225000,127000,CT21,ST27,248001,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,5
4,5,Maruti Swift VXI BSIII,2007,130000,120000,CT03,ST24,600020,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5

In [11]:
sales_status = pd.read_csv('d:/data/cars/Sales_Status.csv')
sales_status.shape

(7906, 2)

In [13]:
sales_status.head()

   Sales_ID Sold
0         1    Y
1         2    Y
2         3    Y
3         4    Y
4         5    Y

In [15]:
sales_status.Sold.value_counts()

Sold
N    5906
Y    2000
Name: count, dtype: int64

In [17]:
city = pd.read_csv('d:/data/cars/City_Master.csv')
city.shape

(29, 3)

In [19]:
city.head()

  City_Code   City_Name State_Code
0      CT01      Mumbai       ST15
1      CT02        Pune       ST15
2      CT03     Chennai       ST24
3      CT04  Coimbatore       ST24
4      CT05   Hyderabad       ST25

In [21]:
state = pd.read_excel('d:/data/cars/State_Master.xlsx')
state.shape

(36, 2)

In [25]:
state.head()

  State_Code         State_Name
0       ST01     Andhra Pradesh
1       ST02  Arunachal Pradesh
2       ST03              Assam
3       ST04              Bihar
4       ST05       Chhattisgarh

In [27]:
cars_sales.State_Code.nunique()

18

In [29]:
cars_sales.City_Code.nunique()

29

In [39]:
cars = pd.merge(left=cars_sales,right=sales_status,on="Sales_ID",how="inner",validate="1:1")
cars.head()

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code,Postal_Code,Fuel,Seller_Type,Transmission,Owner,Mileage,Engine,Max_Power,Seats,Sold
0,1,Maruti Swift Dzire VDI,2014,450000,145500,CT01,ST15,400001,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5,Y
1,2,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,CT28,ST11,834001,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5,Y
2,3,Honda City 2017-2020 EXi,2006,158000,140000,CT12,ST28,201301,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,5,Y
3,4,Hyundai i20 Sportz Diesel,2010,225000,127000,CT21,ST27,248001,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,5,Y
4,5,Maruti Swift VXI BSIII,2007,130000,120000,CT03,ST24,600020,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5,Y

In [41]:
cars = pd.merge(left=cars,right=state,how='inner',on="State_Code",validate="m:1")
cars.head()

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code,Postal_Code,Fuel,Seller_Type,Transmission,Owner,Mileage,Engine,Max_Power,Seats,Sold,State_Name
0,1,Maruti Swift Dzire VDI,2014,450000,145500,CT01,ST15,400001,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5,Y,Maharashtra
1,2,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,CT28,ST11,834001,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5,Y,Jharkhand
2,3,Honda City 2017-2020 EXi,2006,158000,140000,CT12,ST28,201301,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,5,Y,Uttar Pradesh
3,4,Hyundai i20 Sportz Diesel,2010,225000,127000,CT21,ST27,248001,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,5,Y,Uttarakhand
4,5,Maruti Swift VXI BSIII,2007,130000,120000,CT03,ST24,600020,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5,Y,Tamil Nadu

In [43]:
cars = pd.merge(left=cars,right=city[["City_Code","City_Name"]],how='inner',on="City_Code",validate="m:1")
cars.head()

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code,Postal_Code,Fuel,Seller_Type,Transmission,Owner,Mileage,Engine,Max_Power,Seats,Sold,State_Name,City_Name
0,1,Maruti Swift Dzire VDI,2014,450000,145500,CT01,ST15,400001,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5,Y,Maharashtra,Mumbai
1,2,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,CT28,ST11,834001,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5,Y,Jharkhand,Ranchi
2,3,Honda City 2017-2020 EXi,2006,158000,140000,CT12,ST28,201301,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,5,Y,Uttar Pradesh,Noida
3,4,Hyundai i20 Sportz Diesel,2010,225000,127000,CT21,ST27,248001,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,5,Y,Uttarakhand,Dehradun
4,5,Maruti Swift VXI BSIII,2007,130000,120000,CT03,ST24,600020,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5,Y,Tamil Nadu,Chennai

In [45]:
cars.groupby("State_Name").size()

State_Name
Andhra Pradesh    281
Bihar             257
Delhi             320
Gujarat           792
Jharkhand         523
Karnataka         834
Kerala            549
Madhya Pradesh    257
Maharashtra       826
Odisha            255
Punjab            249
Rajasthan         274
Sikkim            257
Tamil Nadu        872
Telangana         262
Uttar Pradesh     550
Uttarakhand       280
West Bengal       268
dtype: int64

In [49]:
cars.groupby(["State_Name","Sold"]).size()

State_Name      Sold
Andhra Pradesh  N       213
                Y        68
Bihar           N       188
                Y        69
Delhi           N       240
                Y        80
Gujarat         N       584
                Y       208
Jharkhand       N       396
                Y       127
Karnataka       N       611
                Y       223
Kerala          N       419
                Y       130
Madhya Pradesh  N       188
                Y        69
Maharashtra     N       637
                Y       189
Odisha          N       191
                Y        64
Punjab          N       186
                Y        63
Rajasthan       N       219
                Y        55
Sikkim          N       188
                Y        69
Tamil Nadu      N       642
                Y       230
Telangana       N       190
                Y        72
Uttar Pradesh   N       405
                Y       145
Uttarakhand     N       210
                Y        70
West Bengal     N       199
                Y        69
dtype: int64

In [57]:
cars[cars.State_Name=="Tamil Nadu"].groupby(["City_Name","Sold"]).size()

City_Name   Sold
Chennai     N       213
            Y        72
Coimbatore  N       217
            Y        77
Vellore     N       212
            Y        81
dtype: int64

In [59]:
cars[cars.State_Name=="Karnataka"].groupby(["City_Name","Sold"]).size()

City_Name  Sold
Bangalore  N       212
           Y        64
Mangalore  N       203
           Y        76
Mysore     N       196
           Y        83
dtype: int64

In [61]:
cars[cars.State_Name=="Telangana"].groupby(["City_Name","Sold"]).size()

City_Name  Sold
Hyderabad  N       190
           Y        72
dtype: int64

In [63]:
cars.groupby(["Seller_Type","Sold"]).size()

Seller_Type       Sold
Dealer            N        816
                  Y        291
Individual        N       4934
                  Y       1629
Trustmark Dealer  N        156
                  Y         80
dtype: int64

In [65]:
cars[cars.State_Name=="Karnataka"].groupby(["City_Name","Seller_Type","Sold"]).size()

City_Name  Seller_Type       Sold
Bangalore  Dealer            N        34
                             Y         7
           Individual        N       173
                             Y        55
           Trustmark Dealer  N         5
                             Y         2
Mangalore  Dealer            N        18
                             Y        12
           Individual        N       177
                             Y        60
           Trustmark Dealer  N         8
                             Y         4
Mysore     Dealer            N        41
                             Y        16
           Individual        N       152
                             Y        66
           Trustmark Dealer  N         3
                             Y         1
dtype: int64

In [79]:
cars[cars.State_Name=="Karnataka"].pivot_table(values="Sales_ID",index="City_Name",columns=["Seller_Type","Sold"],aggfunc="count")

Seller_Type Dealer     Individual     Trustmark Dealer
Sold             N   Y          N   Y                N  Y
City_Name
Bangalore       34   7        173  55                5  2
Mangalore       18  12        177  60                8  4
Mysore          41  16        152  66                3  1