In [1]:
import pandas as pd

In [3]:
cars_sales = pd.read_csv('d:/data/cars/Car_sales_transactions.csv')
cars_sales

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code,Postal_Code,Fuel,Seller_Type,Transmission,Owner,Mileage,Engine,Max_Power,Seats
0,1,Maruti Swift Dzire VDI,2014,450000,145500,CT01,ST15,400001,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5
1,2,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,CT28,ST11,834001,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5
2,3,Honda City 2017-2020 EXi,2006,158000,140000,CT12,ST28,201301,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,5
3,4,Hyundai i20 Sportz Diesel,2010,225000,127000,CT21,ST27,248001,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,5
4,5,Maruti Swift VXI BSIII,2007,130000,120000,CT03,ST24,600020,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7901,8124,Hyundai i20 Magna,2013,320000,110000,CT22,ST14,452010,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,5
7902,8125,Hyundai Verna CRDi SX,2007,135000,119000,CT21,ST27,248001,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,5
7903,8126,Maruti Swift Dzire ZDi,2009,382000,120000,CT08,ST29,700005,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,5
7904,8127,Tata Indigo CR4,2013,290000,25000,CT29,ST24,632001,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,5
7905,8128,Tata Indigo CR4,2013,290000,25000,CT21,ST27,248001,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,5

In [5]:
sale_status = pd.read_csv('d:/data/cars/Sales_Status.csv')
sale_status

      Sales_ID Sold
0            1    Y
1            2    Y
2            3    Y
3            4    Y
4            5    Y
...        ...  ...
7901      8124    N
7902      8125    N
7903      8126    N
7904      8127    N
7905      8128    N

[7906 rows x 2 columns]

In [7]:
cars = pd.concat(objs=[cars_sales,sale_status],axis=1)
cars

,Sales_ID,Name,Year,Selling_Price,km_Driven,City_Code,State_Code,Postal_Code,Fuel,Seller_Type,Transmission,Owner,Mileage,Engine,Max_Power,Seats,Sales_ID,Sold
0,1,Maruti Swift Dzire VDI,2014,450000,145500,CT01,ST15,400001,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5,1,Y
1,2,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,CT28,ST11,834001,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5,2,Y
2,3,Honda City 2017-2020 EXi,2006,158000,140000,CT12,ST28,201301,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,5,3,Y
3,4,Hyundai i20 Sportz Diesel,2010,225000,127000,CT21,ST27,248001,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,5,4,Y
4,5,Maruti Swift VXI BSIII,2007,130000,120000,CT03,ST24,600020,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5,5,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7901,8124,Hyundai i20 Magna,2013,320000,110000,CT22,ST14,452010,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,5,8124,N
7902,8125,Hyundai Verna CRDi SX,2007,135000,119000,CT21,ST27,248001,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,5,8125,N
7903,8126,Maruti Swift Dzire ZDi,2009,382000,120000,CT08,ST29,700005,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,5,8126,N
7904,8127,Tata Indigo CR4,2013,290000,25000,CT29,ST24,632001,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,5,8127,N
7905,8128,Tata Indigo CR4,2013,290000,25000,CT21,ST27,248001,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,5,8128,N

In [9]:
emp1 = pd.read_csv('d:/NewData/EMP1.txt')
emp1

   empno ename
0   1001  ABCD
1   1002   XYZ
2   1003  PQRS
3   1004  EFGH
4   1005  MMMM
5   1006  PPPP
6   1007  IIII
7   1008  NNNN

In [11]:
emp2 = pd.read_csv('d:/NewData/EMP2.txt')
emp2

    sal  deptno
0  2500      20
1  1500      30
2  4000      10
3  1000      20
4  2500      10
5  5000      30
6  2400      10

In [21]:
pd.concat(objs=[emp1,emp2],axis=1,join='outer')

   empno ename     sal  deptno
0   1001  ABCD  2500.0    20.0
1   1002   XYZ  1500.0    30.0
2   1003  PQRS  4000.0    10.0
3   1004  EFGH  1000.0    20.0
4   1005  MMMM  2500.0    10.0
5   1006  PPPP  5000.0    30.0
6   1007  IIII  2400.0    10.0
7   1008  NNNN     NaN     NaN

In [23]:
df1 =  pd.read_csv('d:/data/Hotels/bangalore.csv')
df2 =  pd.read_csv('d:/data/Hotels/chennai.csv')
df3 =  pd.read_csv('d:/data/Hotels/delhi.csv')
df4 =  pd.read_csv('d:/data/Hotels/hyderabad.csv')
df5 =  pd.read_csv('d:/data/Hotels/mumbai.csv')
df6 =  pd.read_csv('d:/data/Hotels/kolkata.csv')

In [25]:
df1.columns

Index(['Hotel Name', 'Rating', 'Rating Description', 'Reviews', 'Star Rating',
       'Location', 'Nearest Landmark', 'Distance to Landmark', 'Price', 'Tax'],
      dtype='object')

In [27]:
df2.columns

Index(['Hotel Name', 'Rating', 'Rating Description', 'Reviews', 'Star Rating',
       'Location', 'Nearest Landmark', 'Distance to Landmark', 'Price', 'Tax'],
      dtype='object')

In [29]:
df6.columns

Index(['Hotel Name', 'Rating', 'Rating Description', 'Reviews', 'Star Rating',
       'Location', 'Nearest Landmark', 'Distance to Landmark', 'Price', 'Tax'],
      dtype='object')

In [31]:
df1.shape,df4.shape

((101, 10), (75, 10))

In [33]:
df1['Rating Description'].value_counts()

Rating Description
Very Good    67
Excellent    28
Good          5
Name: count, dtype: int64

In [41]:
hotels = pd.concat(objs=[df1,df2,df3,df4,df5,df6],axis=0,ignore_index=True)
hotels

,Hotel Name,Rating,Rating Description,Reviews,Star Rating,Location,Nearest Landmark,Distance to Landmark,Price,Tax
0,The Park Bangalore,3.9,Very Good,4187.0,5.0,Ulsoor,NaN,NaN,"7,567","2,254"
1,"Keys Select by Lemon Tree Hotels, Whitefield, ...",4.0,Very Good,2201.0,4.0,Brookefield,NaN,NaN,"1,509",531
2,ITC Windsor - A Luxury Collection Hotel,4.4,Excellent,1315.0,5.0,Vasanth Nagar,Bangalore Palace,2.4 km,"9,900",NaN
3,Lemon Tree Premier Ulsoor Lake Bangalore,4.0,Very Good,5089.0,5.0,Sivanchetti Gardens,Ulsoor Lake,770 m,"2,347",918
4,"Keys Select by Lemon Tree Hotels, Hosur Road, ...",4.0,Very Good,3290.0,4.0,Hosur road,NaN,NaN,"2,522","1,014"
...,...,...,...,...,...,...,...,...,...,...
575,Hotel Gateway Continental,3.8,Very Good,600.0,3.0,Dum Dum,Netaji Subhash Chandra Bose International Airport,1.3 km,"2,800",737
576,Hotel Air View,4.0,Very Good,539.0,NaN,Dum Dum,Netaji Subhash Chandra Bose International Airport,1.8 km,"1,078",255
577,Hotel Casa Fortuna,3.9,Very Good,693.0,3.0,Park Street Area,NaN,NaN,"3,934",950
578,Middleton Inn,3.5,Very Good,264.0,3.0,Park Street,Park Street,710 m,"2,590",545
579,Hotel Sawood International,3.6,Very Good,687.0,3.0,Tangra,NaN,NaN,"2,122",560

In [43]:
hotels['Rating Description'].value_counts()

Rating Description
Very Good    398
Excellent    139
Good          37
Average        4
Poor           1
Name: count, dtype: int64

In [49]:
hotels[hotels['Rating Description']=='Average']

,Hotel Name,Rating,Rating Description,Reviews,Star Rating,Location,Nearest Landmark,Distance to Landmark,Price,Tax
284,HOME@B11,2.3,Average,3.0,NaN,East Of Kailash,NaN,NaN,"2,758",901
294,Centaur Hotel,2.5,Average,676.0,3.0,Delhi Airport,Indira Gandhi International Airport,2.0 km,"3,202",654
339,Katriya Hotel and Towers,2.8,Average,3250.0,3.0,Somajiguda,NaN,NaN,"3,761",451
371,The Manohar,2.7,Average,258.0,3.0,Begumpet,NaN,NaN,"3,158",645

In [53]:
hotels.sort_values(by="Rating")

,Hotel Name,Rating,Rating Description,Reviews,Star Rating,Location,Nearest Landmark,Distance to Landmark,Price,Tax
142,OYO Home Fantasea Uthandi Near Juhu Beach,1.9,Poor,7.0,NaN,Uthandi,NaN,NaN,769,40
284,HOME@B11,2.3,Average,3.0,NaN,East Of Kailash,NaN,NaN,"2,758",901
294,Centaur Hotel,2.5,Average,676.0,3.0,Delhi Airport,Indira Gandhi International Airport,2.0 km,"3,202",654
371,The Manohar,2.7,Average,258.0,3.0,Begumpet,NaN,NaN,"3,158",645
339,Katriya Hotel and Towers,2.8,Average,3250.0,3.0,Somajiguda,NaN,NaN,"3,761",451
...,...,...,...,...,...,...,...,...,...,...
513,Joey's Nest,4.7,Excellent,54.0,NaN,Salt Lake City,Netaji Subhash Chandra Bose International Airport,9.5 km,"2,245",583
428,"The Oberoi, Mumbai",4.7,Excellent,876.0,5.0,Marine Drive,Queen's Necklace - Marine Drive,420 m,"16,750",NaN
432,Afra dormitory,4.8,Excellent,4.0,NaN,Andheri East,T2 - Chhatrapati Shivaji International Airport,3.3 km,848,228
94,Four Seasons Hotel Bengaluru at Embassy One,4.8,Excellent,302.0,5.0,Ganganagar,Palace Grounds,990 m,"14,875",NaN
34,The Hosteller Bangalore Brigade Road,NaN,NaN,NaN,NaN,Ashok Nagar,MG Road,2.2 km,"1,330",315