In [1]:
import pandas as pd 
import numpy as np

In [5]:
marks = np.array([[80,91,88,83,85],[89,85,92,95,90],[91,95,94,85,86]])
marks

array([[80, 91, 88, 83, 85],
       [89, 85, 92, 95, 90],
       [91, 95, 94, 85, 86]])

In [17]:
marks_df =pd.DataFrame(marks,
                       index=['x','y','z'],
                       columns=['maths','physics','chemistry','english','social']
                      )
type(marks_df),marks_df.shape

(pandas.core.frame.DataFrame, (3, 5))

In [18]:
marks_df

   maths  physics  chemistry  english  social
x     80       91         88       83      85
y     89       85         92       95      90
z     91       95         94       85      86

In [20]:
marks_df1 = pd.DataFrame({"maths":[80,89,91],"physics":[91,85,95],"chemistry":[88,92,94],'english':[83,95,85],"social":[85,90,86]},
                        index=['x','y','z'])
marks_df1

   maths  physics  chemistry  english  social
x     80       91         88       83      85
y     89       85         92       95      90
z     91       95         94       85      86

In [21]:
students = pd.DataFrame({"sid":[1001,1002,1002],"sname":['x','y','z'],'course':['java','testing','oracle'],
                         "fees":[5000,4000,35000]})
students

    sid sname   course   fees
0  1001     x     java   5000
1  1002     y  testing   4000
2  1002     z   oracle  35000