In [1]:
import pandas as pd

In [41]:
cars = pd.read_csv('c:/data/usedcars.csv',sep=',',header=0)
cars

     year model  price  mileage   color transmission
0    2011   SEL  21992    74130  Yellow         AUTO
1    2011   SEL  20995    10926    Gray         AUTO
2    2011   SEL  19995     7351  Silver         AUTO
3    2011   SEL  17809    11613    Gray         AUTO
4    2012    SE  17500     8367   White         AUTO
..    ...   ...    ...      ...     ...          ...
145  2006   SES   6200    95000  Silver         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

[150 rows x 6 columns]

In [3]:
wine_red = pd.read_csv('c:/data/winequality-red.csv',sep=';')
wine_red

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [6]:
cars = pd.read_csv('c:/data/usedcars.csv',usecols=[1,2,3,4])
cars

    model  price  mileage   color
0     SEL  21992     7413  Yellow
1     SEL  20995    10926    Gray
2     SEL  19995     7351  Silver
3     SEL  17809    11613    Gray
4      SE  17500     8367   White
..    ...    ...      ...     ...
145   SES   6200    95000  Silver
146    SE   5995    87003     Red
147    SE   5980    96841     Red
148    SE   4899   151479  Yellow
149    SE   3800   109259     Red

[150 rows x 4 columns]

In [8]:
cars = pd.read_csv('c:/data/usedcars.csv',
                   usecols=["model",'price','mileage','color'])
cars

    model  price  mileage   color
0     SEL  21992     7413  Yellow
1     SEL  20995    10926    Gray
2     SEL  19995     7351  Silver
3     SEL  17809    11613    Gray
4      SE  17500     8367   White
..    ...    ...      ...     ...
145   SES   6200    95000  Silver
146    SE   5995    87003     Red
147    SE   5980    96841     Red
148    SE   4899   151479  Yellow
149    SE   3800   109259     Red

[150 rows x 4 columns]

In [12]:
airquality = pd.read_csv('c:/data/AirQuality.csv',sep=';',decimal=',')
airquality

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
iris = pd.read_csv('c:/data/IRIS.csv',header=None,
                  names=["sepal_length","sepal_width","petal_length",'petal_width','species'])
iris

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [31]:
students = pd.read_csv('c:/data/students_marks.csv',header=0,
                      names=["student_name","maths_marks","physics_marks",'chemistry_marks'])
students

  student_name  maths_marks  physics_marks  chemistry_marks
0        vamsi           80             85               35
1      krishna           88             80               75
2        deepa           90             94               88
3        kriti           80             30               82