In [1]:
import pandas as pd

In [6]:
def convert_species(x):
    return x.split("-")[1].lower()

In [26]:
iris = pd.read_csv('c:/data/IRIS.csv',
                   names=['sepal_length','sepal_width','petal_length','petal_width','species'],
                  converters={4:convert_species})
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [21]:
iris = pd.read_csv('c:/data/IRIS.csv',
                   header=None,
                  converters={4:lambda x:x.split("-")[1].capitalize()})
iris

       0    1    2    3          4
0    5.1  3.5  1.4  0.2     Setosa
1    4.9  3.0  1.4  0.2     Setosa
2    4.7  3.2  1.3  0.2     Setosa
3    4.6  3.1  1.5  0.2     Setosa
4    5.0  3.6  1.4  0.2     Setosa
..   ...  ...  ...  ...        ...
145  6.7  3.0  5.2  2.3  Virginica
146  6.3  2.5  5.0  1.9  Virginica
147  6.5  3.0  5.2  2.0  Virginica
148  6.2  3.4  5.4  2.3  Virginica
149  5.9  3.0  5.1  1.8  Virginica

[150 rows x 5 columns]

In [22]:
iris.ndim,iris.shape

(2, (150, 5))

In [24]:
iris.dtypes

0    float64
1    float64
2    float64
3    float64
4     object
dtype: object

In [27]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [29]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [33]:
iris.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [34]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [36]:
pd.read_table('c:/data/usedcars.csv',sep=',')

     year model  price  mileage   color transmission
0    2011   SEL  21992     7413  Yellow         AUTO
1    2011   SEL  20995    10926    Gray         AUTO
2    2011   SEL  19995     7351  Silver         AUTO
3    2011   SEL  17809    11613    Gray         AUTO
4    2012    SE  17500     8367   White         AUTO
..    ...   ...    ...      ...     ...          ...
145  2006   SES   6200    95000  Silver         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

[150 rows x 6 columns]