In [1]:
import pandas as pd

In [4]:
cars_json = pd.read_json('c:/data/cars.json')
cars_json

     year model  price  mileage   color transmission
0    2011   SEL  21992     7413  Yellow         AUTO
1    2011   SEL  20995    10926    Gray         AUTO
2    2011   SEL  19995     7351  Silver         AUTO
3    2011   SEL  17809    11613    Gray         AUTO
4    2012    SE  17500     8367   White         AUTO
..    ...   ...    ...      ...     ...          ...
145  2006   SES   6200    95000  Silver         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

[150 rows x 6 columns]

In [5]:
cars_xml = pd.read_xml('c:/data/cars.xml')
cars_xml

    model  price  mileage   color
0     SEL  21992     7846  Silver
1     SEL  20995    10926    Gray
2     SEL  19995     7351  Silver
3     SEL  17809    11613    Gray
4      SE  17500     8367   White
..    ...    ...      ...     ...
145   SES   6200    95000  Silver
146    SE   5995    87003     Red
147    SE   5980    96841     Red
148    SE   4899   151479  Yellow
149    SE   3800   109259     Red

[150 rows x 4 columns]

In [7]:
cars_hdf = pd.read_hdf('c:/data/cars.hdf')
cars_hdf

    model  price  mileage   color
0     SEL  21992     7413  Yellow
1     SEL  20995    10926    Gray
2     SEL  19995     7351  Silver
3     SEL  17809    11613    Gray
4      SE  17500     8367   White
..    ...    ...      ...     ...
145   SES   6200    95000  Silver
146    SE   5995    87003     Red
147    SE   5980    96841     Red
148    SE   4899   151479  Yellow
149    SE   3800   109259     Red

[150 rows x 4 columns]

In [8]:
airlines_sas = pd.read_sas('c:/data/airline.sas7bdat')
airlines_sas

      YEAR          Y      W       R      L      K
0   1948.0   1.214000  0.243  0.1454  1.415  0.612
1   1949.0   1.354000  0.260  0.2181  1.384  0.559
2   1950.0   1.569000  0.278  0.3157  1.388  0.573
3   1951.0   1.948000  0.297  0.3940  1.550  0.564
4   1952.0   2.265000  0.310  0.3559  1.802  0.574
5   1953.0   2.731000  0.322  0.3593  1.926  0.711
6   1954.0   3.025000  0.335  0.4025  1.964  0.776
7   1955.0   3.562000  0.350  0.3961  2.116  0.827
8   1956.0   3.979000  0.361  0.3822  2.435  0.800
9   1957.0   4.420000  0.379  0.3045  2.707  0.921
10  1958.0   4.563000  0.391  0.3284  2.706  1.067
11  1959.0   5.385000  0.426  0.3856  2.846  1.083
12  1960.0   5.554000  0.441  0.3193  3.089  1.481
13  1961.0   5.465000  0.460  0.3079  3.122  1.736
14  1962.0   5.825000  0.485  0.3783  3.184  1.926
15  1963.0   6.876000  0.506  0.4180  3.263  2.041
16  1964.0   7.823000  0.538  0.5163  3.412  1.997
17  1965.0   9.120000  0.564  0.5879  3.623  2.257
18  1966.0  10.512000  0.586  0.5369  4.074  2.742
19  1967.0  13.020000  0.622  0.4443  4.710  3.564
20  1968.0  15.261000  0.666  0.3052  5.217  4.767
21  1969.0  16.313000  0.731  0.2332  5.569  6.511
22  1970.0  16.002001  0.831  0.1883  5.495  7.627
23  1971.0  15.876000  0.906  0.2023  5.334  8.673
24  1972.0  16.662001  1.000  0.2506  5.345  8.331
25  1973.0  17.014000  1.056  0.2668  5.662  8.557
26  1974.0  19.305000  1.131  0.2664  5.729  9.508
27  1975.0  18.721001  1.247  0.2301  5.722  9.062
28  1976.0  19.250000  1.375  0.3452  5.762  8.262
29  1977.0  20.646999  1.544  0.4508  5.877  7.474
30  1978.0  22.726000  1.703  0.5877  6.108  7.104
31  1979.0  23.618999  1.779  0.5346  6.852  6.874

In [9]:
airlines_dta = pd.read_stata('c:/data/airline.dta')
airlines_dta

    year          y      w       r      l      k
0   1948   1.214000  0.243  0.1454  1.415  0.612
1   1949   1.354000  0.260  0.2181  1.384  0.559
2   1950   1.569000  0.278  0.3157  1.388  0.573
3   1951   1.948000  0.297  0.3940  1.550  0.564
4   1952   2.265000  0.310  0.3559  1.802  0.574
5   1953   2.731000  0.322  0.3593  1.926  0.711
6   1954   3.025000  0.335  0.4025  1.964  0.776
7   1955   3.562000  0.350  0.3961  2.116  0.827
8   1956   3.979000  0.361  0.3822  2.435  0.800
9   1957   4.420000  0.379  0.3045  2.707  0.921
10  1958   4.563000  0.391  0.3284  2.706  1.067
11  1959   5.385000  0.426  0.3856  2.846  1.083
12  1960   5.554000  0.441  0.3193  3.089  1.481
13  1961   5.465000  0.460  0.3079  3.122  1.736
14  1962   5.825000  0.485  0.3783  3.184  1.926
15  1963   6.876000  0.506  0.4180  3.263  2.041
16  1964   7.823000  0.538  0.5163  3.412  1.997
17  1965   9.120000  0.564  0.5879  3.623  2.257
18  1966  10.512000  0.586  0.5369  4.074  2.742
19  1967  13.020000  0.622  0.4443  4.710  3.564
20  1968  15.261000  0.666  0.3052  5.217  4.767
21  1969  16.313000  0.731  0.2332  5.569  6.511
22  1970  16.002001  0.831  0.1883  5.495  7.627
23  1971  15.876000  0.906  0.2023  5.334  8.673
24  1972  16.662001  1.000  0.2506  5.345  8.331
25  1973  17.014000  1.056  0.2668  5.662  8.557
26  1974  19.305000  1.131  0.2664  5.729  9.508
27  1975  18.721001  1.247  0.2301  5.722  9.062
28  1976  19.250000  1.375  0.3452  5.762  8.262
29  1977  20.646999  1.544  0.4508  5.877  7.474
30  1978  22.726000  1.703  0.5877  6.108  7.104
31  1979  23.618999  1.779  0.5346  6.852  6.874

In [12]:
df_spss = pd.read_spss('c:/data/loan_roc.sav')
df_spss.shape

(100, 13)

In [13]:
df_spss.head()

,age,education,year_emp,income,debt_income,cred_debt,other_debt,Loan,Logistc,PGR_1,Dis_1,Dis1_1,Discrim
0,47.0,Did not complete high school,22.0,81.0,5.5,1.505790,2.949210,No,0.000625,No,No,0.988438,0.011562
1,40.0,Did not complete high school,22.0,95.0,3.6,0.632700,2.787300,No,0.001633,No,No,0.973334,0.026666
2,35.0,Did not complete high school,16.0,36.0,3.4,0.178704,1.045296,No,0.000966,No,No,0.988864,0.011136
3,43.0,Did not complete high school,16.0,89.0,0.4,0.159488,0.196512,No,0.001386,No,No,0.974100,0.025900
4,47.0,Did not complete high school,26.0,100.0,12.8,4.582400,8.217600,No,0.012345,No,No,0.931966,0.068034

In [18]:
employees = pd.read_fwf('c:/data/sample_fwf.csv',names=['empno','ename','salary','deptno'],widths=[4,6,5,2])
employees

   empno   ename  salary  deptno
0   1001  abcdef   25000      20
1   1002  wxyzab   50000      30
2   1003  efghij   30000      10