In [1]:
import pandas as pd

In [2]:
cars = pd.read_csv('c:/data/usedcars.csv')
cars.head()

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO

In [3]:
cars.columns

Index(['year', 'model', 'price', 'mileage', 'color', 'transmission'], dtype='object')

In [4]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          150 non-null    int64
 1   model         150 non-null    object
 2   price         150 non-null    int64
 3   mileage       150 non-null    int64
 4   color         150 non-null    object
 5   transmission  150 non-null    object
dtypes: int64(3), object(3)
memory usage: 7.2+ KB

In [6]:
cars.tail()

     year model  price  mileage   color transmission
145  2006   SES   6200    95000  Silver         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

In [7]:
cars[:5]

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO

In [8]:
cars[-5:]

     year model  price  mileage   color transmission
145  2006   SES   6200    95000  Silver         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

In [10]:
cars[::-2]

     year model  price  mileage   color transmission
149  2000    SE   3800   109259     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
145  2006   SES   6200    95000  Silver         AUTO
143  2004   SES   6980   101130    Gray         AUTO
141  2007    SE   6995    86862   White         AUTO
..    ...   ...    ...      ...     ...          ...
9    2010   SES  16995    36116  Silver         AUTO
7    2010   SEL  16995    21026  Silver         AUTO
5    2010   SEL  17495    25125  Silver         AUTO
3    2011   SEL  17809    11613    Gray         AUTO
1    2011   SEL  20995    10926    Gray         AUTO

[75 rows x 6 columns]

In [12]:
cars[5:6]

   year model  price  mileage   color transmission
5  2010   SEL  17495    25125  Silver         AUTO

In [20]:
cars['price']

0      21992
1      20995
2      19995
3      17809
4      17500
       ...
145     6200
146     5995
147     5980
148     4899
149     3800
Name: price, Length: 150, dtype: int64

In [30]:
cars[['price','model','mileage','color']]

     price model  mileage   color
0    21992   SEL     7413  Yellow
1    20995   SEL    10926    Gray
2    19995   SEL     7351  Silver
3    17809   SEL    11613    Gray
4    17500    SE     8367   White
..     ...   ...      ...     ...
145   6200   SES    95000  Silver
146   5995    SE    87003     Red
147   5980    SE    96841     Red
148   4899    SE   151479  Yellow
149   3800    SE   109259     Red

[150 rows x 4 columns]

In [33]:
cars[:10][['model','price','mileage']]

  model  price  mileage
0   SEL  21992     7413
1   SEL  20995    10926
2   SEL  19995     7351
3   SEL  17809    11613
4    SE  17500     8367
5   SEL  17495    25125
6   SEL  17000    27393
7   SEL  16995    21026
8   SES  16995    32655
9   SES  16995    36116

In [35]:
cars[['model','price','mileage']][:10]

  model  price  mileage
0   SEL  21992     7413
1   SEL  20995    10926
2   SEL  19995     7351
3   SEL  17809    11613
4    SE  17500     8367
5   SEL  17495    25125
6   SEL  17000    27393
7   SEL  16995    21026
8   SES  16995    32655
9   SES  16995    36116

In [36]:
cars.head()

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO

In [43]:
cars[:10][['mileage','price','color','model']]

   mileage  price   color model
0     7413  21992  Yellow   SEL
1    10926  20995    Gray   SEL
2     7351  19995  Silver   SEL
3    11613  17809    Gray   SEL
4     8367  17500   White    SE
5    25125  17495  Silver   SEL
6    27393  17000    Blue   SEL
7    21026  16995  Silver   SEL
8    32655  16995  Silver   SES
9    36116  16995  Silver   SES

In [44]:
cars.iloc[:10,1:4]

  model  price  mileage
0   SEL  21992     7413
1   SEL  20995    10926
2   SEL  19995     7351
3   SEL  17809    11613
4    SE  17500     8367
5   SEL  17495    25125
6   SEL  17000    27393
7   SEL  16995    21026
8   SES  16995    32655
9   SES  16995    36116

In [51]:
cars.iloc[[2,15,126,93,84,23,1,0,10,25],[2,3,1,4]]

     price  mileage model   color
2    19995     7351   SEL  Silver
15   15999    16368   SES    Blue
126   9992    74109    SE   White
93   12849    29517    SE  Silver
84   12995    32743    SE   Black
23   15889    24920   SEL   Black
1    20995    10926   SEL    Gray
0    21992     7413   SEL  Yellow
10   16995    40539   SEL   Black
25   15500    29338    SE    Blue

In [54]:
cars.iloc[::-2,::-1]

    transmission   color  mileage  price model  year
149         AUTO     Red   109259   3800    SE  2000
147         AUTO     Red    96841   5980    SE  2000
145         AUTO  Silver    95000   6200   SES  2006
143         AUTO    Gray   101130   6980   SES  2004
141         AUTO   White    86862   6995    SE  2007
..           ...     ...      ...    ...   ...   ...
9           AUTO  Silver    36116  16995   SES  2010
7           AUTO  Silver    21026  16995   SEL  2010
5           AUTO  Silver    25125  17495   SEL  2010
3           AUTO    Gray    11613  17809   SEL  2011
1           AUTO    Gray    10926  20995   SEL  2011

[75 rows x 6 columns]