In [1]:
import pandas as pd

In [2]:
cars = pd.read_csv('c:/data/usedcars.csv')
cars.shape

(150, 6)

In [4]:
cars

     year model  price  mileage   color transmission
0    2011   SEL  21992     7413  Yellow         AUTO
1    2011   SEL  20995    10926    Gray         AUTO
2    2011   SEL  19995     7351  Silver         AUTO
3    2011   SEL  17809    11613    Gray         AUTO
4    2012    SE  17500     8367   White         AUTO
..    ...   ...    ...      ...     ...          ...
145  2006   SES   6200    95000  Silver         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

[150 rows x 6 columns]

In [5]:
cars.columns

Index(['year', 'model', 'price', 'mileage', 'color', 'transmission'], dtype='object')

In [6]:
cars.index

RangeIndex(start=0, stop=150, step=1)

In [9]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          150 non-null    int64
 1   model         150 non-null    object
 2   price         150 non-null    int64
 3   mileage       150 non-null    int64
 4   color         150 non-null    object
 5   transmission  150 non-null    object
dtypes: int64(3), object(3)
memory usage: 7.2+ KB

In [17]:
cars = pd.read_csv('c:/data/usedcars.csv',index_col="color")
cars.shape

(150, 5)

In [18]:
cars

        year model  price  mileage transmission
color
Yellow  2011   SEL  21992     7413         AUTO
Gray    2011   SEL  20995    10926         AUTO
Silver  2011   SEL  19995     7351         AUTO
Gray    2011   SEL  17809    11613         AUTO
White   2012    SE  17500     8367         AUTO
...      ...   ...    ...      ...          ...
Silver  2006   SES   6200    95000         AUTO
Red     2002    SE   5995    87003         AUTO
Red     2000    SE   5980    96841         AUTO
Yellow  2001    SE   4899   151479         AUTO
Red     2000    SE   3800   109259         AUTO

[150 rows x 5 columns]

In [12]:
cars.index

Index(['SEL', 'SEL', 'SEL', 'SEL', 'SE', 'SEL', 'SEL', 'SEL', 'SES', 'SES',
       ...
       'SE', 'SE', 'SE', 'SES', 'SES', 'SES', 'SE', 'SE', 'SE', 'SE'],
      dtype='object', name='model', length=150)

In [13]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, SEL to SE
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          150 non-null    int64
 1   price         150 non-null    int64
 2   mileage       150 non-null    int64
 3   color         150 non-null    object
 4   transmission  150 non-null    object
dtypes: int64(3), object(2)
memory usage: 7.0+ KB

In [14]:
cars.head()

       year  price  mileage   color transmission
model
SEL    2011  21992     7413  Yellow         AUTO
SEL    2011  20995    10926    Gray         AUTO
SEL    2011  19995     7351  Silver         AUTO
SEL    2011  17809    11613    Gray         AUTO
SE     2012  17500     8367   White         AUTO

In [19]:
cars = pd.read_csv('c:/data/usedcars.csv')
cars.shape

(150, 6)

In [20]:
cars

     year model  price  mileage   color transmission
0    2011   SEL  21992     7413  Yellow         AUTO
1    2011   SEL  20995    10926    Gray         AUTO
2    2011   SEL  19995     7351  Silver         AUTO
3    2011   SEL  17809    11613    Gray         AUTO
4    2012    SE  17500     8367   White         AUTO
..    ...   ...    ...      ...     ...          ...
145  2006   SES   6200    95000  Silver         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

[150 rows x 6 columns]

In [21]:
cars.index

RangeIndex(start=0, stop=150, step=1)

In [47]:
cars.set_index(keys="model",drop=True,append=False,inplace=True)  # i=i+10

In [48]:
cars.index

Index(['SEL', 'SEL', 'SEL', 'SEL', 'SE', 'SEL', 'SEL', 'SEL', 'SES', 'SES',
       ...
       'SE', 'SE', 'SE', 'SES', 'SES', 'SES', 'SE', 'SE', 'SE', 'SE'],
      dtype='object', name='model', length=150)

In [49]:
cars

       year  price  mileage   color transmission
model
SEL    2011  21992     7413  Yellow         AUTO
SEL    2011  20995    10926    Gray         AUTO
SEL    2011  19995     7351  Silver         AUTO
SEL    2011  17809    11613    Gray         AUTO
SE     2012  17500     8367   White         AUTO
...     ...    ...      ...     ...          ...
SES    2006   6200    95000  Silver         AUTO
SE     2002   5995    87003     Red         AUTO
SE     2000   5980    96841     Red         AUTO
SE     2001   4899   151479  Yellow         AUTO
SE     2000   3800   109259     Red         AUTO

[150 rows x 5 columns]