In [1]:
import pandas as pd

In [5]:
iris = pd.read_csv('c:/data/iris.csv',
                   names=['sepal_length','sepal_width','petal_length','petal_width','species'],
                   converters={"species":lambda x:x.split("-")[1]})
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
iris.set_index(keys="species",drop=True,append=False,inplace=True)

In [9]:
iris.head()

         sepal_length  sepal_width  petal_length  petal_width
species
setosa            5.1          3.5           1.4          0.2
setosa            4.9          3.0           1.4          0.2
setosa            4.7          3.2           1.3          0.2
setosa            4.6          3.1           1.5          0.2
setosa            5.0          3.6           1.4          0.2

In [10]:
cars = pd.read_csv('c:/data/usedcars.csv',index_col="model")
cars.head()

       year  price  mileage   color transmission
model
SEL    2011  21992     7413  Yellow         AUTO
SEL    2011  20995    10926    Gray         AUTO
SEL    2011  19995     7351  Silver         AUTO
SEL    2011  17809    11613    Gray         AUTO
SE     2012  17500     8367   White         AUTO

In [15]:
cars.set_index(keys='color',drop=True,append=False,inplace=True)

In [16]:
cars

        year  price  mileage transmission
color
Yellow  2011  21992     7413         AUTO
Gray    2011  20995    10926         AUTO
Silver  2011  19995     7351         AUTO
Gray    2011  17809    11613         AUTO
White   2012  17500     8367         AUTO
...      ...    ...      ...          ...
Silver  2006   6200    95000         AUTO
Red     2002   5995    87003         AUTO
Red     2000   5980    96841         AUTO
Yellow  2001   4899   151479         AUTO
Red     2000   3800   109259         AUTO

[150 rows x 4 columns]

In [18]:
cars.set_index(keys='year',drop=True,append=False,inplace=True)

In [19]:
cars

      price  mileage transmission
year
2011  21992     7413         AUTO
2011  20995    10926         AUTO
2011  19995     7351         AUTO
2011  17809    11613         AUTO
2012  17500     8367         AUTO
...     ...      ...          ...
2006   6200    95000         AUTO
2002   5995    87003         AUTO
2000   5980    96841         AUTO
2001   4899   151479         AUTO
2000   3800   109259         AUTO

[150 rows x 3 columns]

In [20]:
cars = pd.read_csv('c:/data/usedcars.csv')
cars.head()

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO

In [21]:
cars.index

RangeIndex(start=0, stop=150, step=1)

In [52]:
cars.set_index(keys="year",drop=True,append=False,inplace=True)
cars

KeyError: "None of ['year'] are in the columns"

In [63]:
cars.head()

      price  mileage transmission
year
2011  21992     7413         AUTO
2011  20995    10926         AUTO
2011  19995     7351         AUTO
2011  17809    11613         AUTO
2012  17500     8367         AUTO

In [71]:
cars.index

Index([2011, 2011, 2011, 2011, 2012, 2010, 2011, 2010, 2011, 2010,
       ...
       2004, 2007, 2000, 2004, 2004, 2006, 2002, 2000, 2001, 2000],
      dtype='int64', name='year', length=150)

In [74]:
cars.reset_index(level='year',drop=False,inplace=True)

KeyError: 'Requested level (year) does not match index name (None)'

In [103]:
cars = pd.read_csv('c:/data/usedcars.csv')
cars.head()

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO

In [116]:
cars.set_index(keys='model',drop=False,append=True,inplace=True)
cars.head()

                                                                               year  \
model model model model model model model model model model model model model
SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL    2011
                                                                        SEL    2011
                                                                        SEL    2011
                                                                        SEL    2011
SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE     2012

                                                                              model  \
model model model model model model model model model model model model model
SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL     SEL
                                                                        SEL     SEL
                                                                        SEL     SEL
                                                                        SEL     SEL
SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE       SE

                                                                               price  \
model model model model model model model model model model model model model
SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL    21992
                                                                        SEL    20995
                                                                        SEL    19995
                                                                        SEL    17809
SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE     17500

                                                                               mileage  \
model model model model model model model model model model model model model
SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL       7413
                                                                        SEL      10926
                                                                        SEL       7351
                                                                        SEL      11613
SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE        8367

                                                                                color  \
model model model model model model model model model model model model model
SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL    Yellow
                                                                        SEL      Gray
                                                                        SEL    Silver
                                                                        SEL      Gray
SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE      White

                                                                              transmission
model model model model model model model model model model model model model
SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL   SEL           AUTO
                                                                        SEL           AUTO
                                                                        SEL           AUTO
                                                                        SEL           AUTO
SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE    SE            AUTO

In [127]:
cars[cars.model=='SES']

     year model  price  mileage   color transmission
8    2011   SES  16995    32655  Silver         AUTO
9    2010   SES  16995    36116  Silver         AUTO
11   2011   SES  16992     9199  Silver         AUTO
13   2010   SES  16950    32058     Red         AUTO
15   2011   SES  15999    16368    Blue         AUTO
17   2010   SES  15995    36049  Silver         AUTO
20   2010   SES  15988    16035  Silver       MANUAL
28   2010   SES  15298    22029    Gray         AUTO
30   2010   SES  14999    36306     Red         AUTO
34   2009   SES  14992    24030     Red         AUTO
40   2010   SES  14761    44813   Black         AUTO
41   2010   SES  14699    36469    Gray         AUTO
42   2010   SES  14677    22143   Black       MANUAL
43   2009   SES  14549    34046  Silver         AUTO
45   2010   SES  14495    35894  Silver         AUTO
51   2010   SES  14275    35318   Black         AUTO
52   2010   SES  14000    24929  Silver         AUTO
57   2009   SES  13995    46126   Black         AUTO
58   2009   SES  13995    53733  Silver         AUTO
59   2009   SES  13992    21108  Silver         AUTO
61   2010   SES  13992    26716    Gray       MANUAL
62   2009   SES  13992    26887   Black         AUTO
70   2009   SES  13799    34888   Black         AUTO
71   2009   SES  13742    38380   Black         AUTO
74   2010   SES  13599    33302     Red         AUTO
76   2009   SES  13425    64055   Black         AUTO
80   2009   SES  12999    32403    Blue         AUTO
91   2009   SES  12990    45813  Silver         AUTO
96   2008   SES  12704    36323    Blue         AUTO
97   2009   SES  12595    39211    Blue         AUTO
104  2009   SES  11984    59048   Black         AUTO
108  2008   SES  11749    57341     Red         AUTO
109  2008   SES  11495    82221  Silver         AUTO
111  2009   SES  10995    42834     Red         AUTO
112  2005   SES  10995    69415    Blue         AUTO
118  2007   SES  10815    77231     Red         AUTO
121  2007   SES  10000    63926     Red         AUTO
122  2007   SES   9999    74427  Silver         AUTO
123  2007   SES   9999    78948   Black       MANUAL
128  2007   SES   9000    80605     Red         AUTO
135  2007   SES   7999    81596  Yellow       MANUAL
136  2006   SES   7995    35000   Black       MANUAL
137  2006   SES   7995    97987     Red         AUTO
138  2003   SES   7900    96000   White         AUTO
139  2005   SES   7488    59013     Red         AUTO
143  2004   SES   6980   101130    Gray         AUTO
144  2004   SES   6950   119720   Black         AUTO
145  2006   SES   6200    95000  Silver         AUTO

In [130]:
cars[cars.price>20000]

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO

In [133]:
cars[(cars.model=='SE') & (cars.color=='White')]

     year model  price  mileage  color transmission
4    2012    SE  17500     8367  White         AUTO
14   2011    SE  16000    15367  White         AUTO
36   2011    SE  14989    23967  White         AUTO
38   2010    SE  14900    28955  White         AUTO
39   2010    SE  14893    11165  White         AUTO
68   2009    SE  13888    50533  White         AUTO
85   2010    SE  12995    40058  White       MANUAL
99   2008    SE  12500    45996  White       MANUAL
100  2009    SE  12500    54988  White       MANUAL
125  2008    SE   9995    95364  White         AUTO
126  2008    SE   9992    74109  White         AUTO
131  2006    SE   8800    71331  White         AUTO
134  2009    SE   8480    70036  White       MANUAL
141  2007    SE   6995    86862  White         AUTO

In [137]:
cars.query("model in('SE','SEL') and color=='Black'")

     year model  price  mileage  color transmission
10   2010   SEL  16995    40539  Black         AUTO
23   2010   SEL  15889    24920  Black         AUTO
26   2010    SE  15499     7784  Black         AUTO
27   2010    SE  15499    35636  Black         AUTO
31   2009    SE  14995    34419  Black       MANUAL
32   2011    SE  14992     4867  Black         AUTO
33   2011   SEL  14992    18948  Black         AUTO
35   2010   SEL  14990    33036  Black         AUTO
46   2010    SE  14495    38275  Black         AUTO
50   2010    SE  14299    36447  Black         AUTO
54   2010    SE  13997    15167  Black       MANUAL
56   2010    SE  13995    20278  Black       MANUAL
64   2009    SE  13950     9450  Black         AUTO
65   2010    SE  13950    31414  Black         AUTO
78   2010    SE  13383    34503  Black         AUTO
83   2010    SE  12995    21325  Black         AUTO
84   2010    SE  12995    32743  Black       MANUAL
94   2010    SE  12780    35871  Black         AUTO
95   2008    SE  12777    49787  Black       MANUAL
103  2009    SE  11992    32559  Black       MANUAL
107  2008    SE  11754    38286  Black         AUTO
120  2010    SE  10717    64199  Black         AUTO
132  2008    SE   8495   106171  Black         AUTO