In [1]:
import pandas as pd

In [3]:
cars = pd.read_csv('c:/data/usedcars.csv')
cars.head()

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO

In [4]:
cars[cars.model=='SE']

     year model  price  mileage   color transmission
4    2012    SE  17500     8367   White         AUTO
14   2011    SE  16000    15367   White         AUTO
22   2011    SE  15899    36685  Silver         AUTO
25   2010    SE  15500    29338    Blue         AUTO
26   2010    SE  15499     7784   Black         AUTO
..    ...   ...    ...      ...     ...          ...
142  2000    SE   6980    60161   Green         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

[78 rows x 6 columns]

In [8]:
cars.query("model in('SES','SE')")

     year model  price  mileage   color transmission
4    2012    SE  17500     8367   White         AUTO
8    2011   SES  16995    32655  Silver         AUTO
9    2010   SES  16995    36116  Silver         AUTO
11   2011   SES  16992     9199  Silver         AUTO
13   2010   SES  16950    32058     Red         AUTO
..    ...   ...    ...      ...     ...          ...
145  2006   SES   6200    95000  Silver         AUTO
146  2002    SE   5995    87003     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
149  2000    SE   3800   109259     Red         AUTO

[126 rows x 6 columns]

In [9]:
cars.set_index(keys="model",inplace=True)
cars.head()

       year  price  mileage   color transmission
model
SEL    2011  21992     7413  Yellow         AUTO
SEL    2011  20995    10926    Gray         AUTO
SEL    2011  19995     7351  Silver         AUTO
SEL    2011  17809    11613    Gray         AUTO
SE     2012  17500     8367   White         AUTO

In [11]:
cars.columns

Index(['year', 'price', 'mileage', 'color', 'transmission'], dtype='object')

In [16]:
cars.loc[["SES",'SE'],["price",'mileage','color']]

       price  mileage   color
model
SES    16995    32655  Silver
SES    16995    36116  Silver
SES    16992     9199  Silver
SES    16950    32058     Red
SES    15999    16368    Blue
...      ...      ...     ...
SE      6980    60161   Green
SE      5995    87003     Red
SE      5980    96841     Red
SE      4899   151479  Yellow
SE      3800   109259     Red

[126 rows x 3 columns]

In [19]:
wine_red = pd.read_csv('c:/data/winequality-red.csv',sep=';',index_col="quality")
wine_red.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
quality,,,,,,,,,,,
5,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4
5,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8
5,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8
6,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8
5,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4

In [28]:
wine_red.loc[[6,5],"fixed acidity":"chlorides"]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides
quality,,,,,
6,11.2,0.280,0.56,1.9,0.075
6,7.9,0.320,0.51,1.8,0.341
6,8.9,0.220,0.48,1.8,0.077
6,6.9,0.400,0.14,2.4,0.085
6,7.8,0.645,0.00,2.0,0.082
...,...,...,...,...,...
5,6.1,0.715,0.10,2.6,0.053
5,6.2,0.460,0.29,2.1,0.074
5,6.6,0.725,0.20,7.8,0.073
5,6.2,0.600,0.08,2.0,0.090
5,5.9,0.645,0.12,2.0,0.075

In [30]:
cars = pd.read_csv('c:/data/usedcars.csv')
cars.head(10)

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO
5  2010   SEL  17495    25125  Silver         AUTO
6  2011   SEL  17000    27393    Blue         AUTO
7  2010   SEL  16995    21026  Silver         AUTO
8  2011   SES  16995    32655  Silver         AUTO
9  2010   SES  16995    36116  Silver         AUTO

In [41]:
cars_new = cars.sample(40)
cars_new

     year model  price  mileage   color transmission
65   2010    SE  13950    31414   Black         AUTO
10   2010   SEL  16995    40539   Black         AUTO
83   2010    SE  12995    21325   Black         AUTO
104  2009   SES  11984    59048   Black         AUTO
54   2010    SE  13997    15167   Black       MANUAL
142  2000    SE   6980    60161   Green         AUTO
34   2009   SES  14992    24030     Red         AUTO
137  2006   SES   7995    97987     Red         AUTO
75   2009   SEL  13584    43369     Red         AUTO
109  2008   SES  11495    82221  Silver         AUTO
115  2008    SE  10955    39643    Gray         AUTO
119  2007    SE  10770    72937  Silver       MANUAL
125  2008    SE   9995    95364   White         AUTO
7    2010   SEL  16995    21026  Silver         AUTO
47   2010    SE  14480    24855    Blue         AUTO
37   2010    SE  14906    37905  Silver         AUTO
136  2006   SES   7995    35000   Black       MANUAL
77   2010    SE  13384    41342    Gray         AUTO
107  2008    SE  11754    38286   Black         AUTO
69   2009    SE  13845    36713    Blue         AUTO
81   2009    SE  12998    34846    Blue         AUTO
148  2001    SE   4899   151479  Yellow         AUTO
30   2010   SES  14999    36306     Red         AUTO
147  2000    SE   5980    96841     Red         AUTO
116  2009    SE  10955    40180    Gold         AUTO
80   2009   SES  12999    32403    Blue         AUTO
113  2009   SEL  10995    78264    Gray         AUTO
12   2011   SEL  16950     9388   Green         AUTO
111  2009   SES  10995    42834     Red         AUTO
70   2009   SES  13799    34888   Black         AUTO
149  2000    SE   3800   109259     Red         AUTO
140  2004    SE   6999   105714  Silver         AUTO
59   2009   SES  13992    21108  Silver         AUTO
127  2007    SE   9651    63296    Blue         AUTO
78   2010    SE  13383    34503   Black         AUTO
62   2009   SES  13992    26887   Black         AUTO
13   2010   SES  16950    32058     Red         AUTO
38   2010    SE  14900    28955   White         AUTO
103  2009    SE  11992    32559   Black       MANUAL
22   2011    SE  15899    36685  Silver         AUTO

In [42]:
cars.iloc[10:30]

    year model  price  mileage   color transmission
10  2010   SEL  16995    40539   Black         AUTO
11  2011   SES  16992     9199  Silver         AUTO
12  2011   SEL  16950     9388   Green         AUTO
13  2010   SES  16950    32058     Red         AUTO
14  2011    SE  16000    15367   White         AUTO
15  2011   SES  15999    16368    Blue         AUTO
16  2010   SEL  15999    19926  Silver         AUTO
17  2010   SES  15995    36049  Silver         AUTO
18  2011   SEL  15992    11662    Blue         AUTO
19  2011   SEL  15992    32069  Silver         AUTO
20  2010   SES  15988    16035  Silver       MANUAL
21  2010   SEL  15980    39943   White         AUTO
22  2011    SE  15899    36685  Silver         AUTO
23  2010   SEL  15889    24920   Black         AUTO
24  2009   SEL  15688    20019    Blue         AUTO
25  2010    SE  15500    29338    Blue         AUTO
26  2010    SE  15499     7784   Black         AUTO
27  2010    SE  15499    35636   Black         AUTO
28  2010   SES  15298    22029    Gray         AUTO
29  2009   SEL  14999    33107  Silver         AUTO

In [46]:
cars_new.iloc[10:34].shape

(24, 6)

In [47]:
cars_new.loc[10:34].shape

(6, 6)

In [49]:
cars.iloc[1:10]

   year model  price  mileage   color transmission
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO
5  2010   SEL  17495    25125  Silver         AUTO
6  2011   SEL  17000    27393    Blue         AUTO
7  2010   SEL  16995    21026  Silver         AUTO
8  2011   SES  16995    32655  Silver         AUTO
9  2010   SES  16995    36116  Silver         AUTO

In [50]:
cars.loc[1:10]

    year model  price  mileage   color transmission
1   2011   SEL  20995    10926    Gray         AUTO
2   2011   SEL  19995     7351  Silver         AUTO
3   2011   SEL  17809    11613    Gray         AUTO
4   2012    SE  17500     8367   White         AUTO
5   2010   SEL  17495    25125  Silver         AUTO
6   2011   SEL  17000    27393    Blue         AUTO
7   2010   SEL  16995    21026  Silver         AUTO
8   2011   SES  16995    32655  Silver         AUTO
9   2010   SES  16995    36116  Silver         AUTO
10  2010   SEL  16995    40539   Black         AUTO

In [54]:
cars_new.iloc[:5]

     year model  price  mileage  color transmission
65   2010    SE  13950    31414  Black         AUTO
10   2010   SEL  16995    40539  Black         AUTO
83   2010    SE  12995    21325  Black         AUTO
104  2009   SES  11984    59048  Black         AUTO
54   2010    SE  13997    15167  Black       MANUAL

In [55]:
cars_new.loc[65:54]

     year model  price  mileage  color transmission
65   2010    SE  13950    31414  Black         AUTO
10   2010   SEL  16995    40539  Black         AUTO
83   2010    SE  12995    21325  Black         AUTO
104  2009   SES  11984    59048  Black         AUTO
54   2010    SE  13997    15167  Black       MANUAL

In [59]:
cars.set_index(keys="color",inplace=True)

In [60]:
cars

        year model  price  mileage transmission
color
Yellow  2011   SEL  21992     7413         AUTO
Gray    2011   SEL  20995    10926         AUTO
Silver  2011   SEL  19995     7351         AUTO
Gray    2011   SEL  17809    11613         AUTO
White   2012    SE  17500     8367         AUTO
...      ...   ...    ...      ...          ...
Silver  2006   SES   6200    95000         AUTO
Red     2002    SE   5995    87003         AUTO
Red     2000    SE   5980    96841         AUTO
Yellow  2001    SE   4899   151479         AUTO
Red     2000    SE   3800   109259         AUTO

[150 rows x 5 columns]

In [63]:
cars.loc[['Blue','Black']]

       year model  price  mileage transmission
color
Blue   2011   SEL  17000    27393         AUTO
Blue   2011   SES  15999    16368         AUTO
Blue   2011   SEL  15992    11662         AUTO
Blue   2009   SEL  15688    20019         AUTO
Blue   2010    SE  15500    29338         AUTO
Blue   2010    SE  14480    24855         AUTO
Blue   2010    SE  13950    37185         AUTO
Blue   2009    SE  13845    36713         AUTO
Blue   2010    SE  13350    16573         AUTO
Blue   2009   SES  12999    32403         AUTO
Blue   2009    SE  12998    34846         AUTO
Blue   2009    SE  12995    42325         AUTO
Blue   2008   SES  12704    36323         AUTO
Blue   2009   SES  12595    39211         AUTO
Blue   2009    SE  11999    36124         AUTO
Blue   2005   SES  10995    69415         AUTO
Blue   2007    SE   9651    63296         AUTO
Black  2010   SEL  16995    40539         AUTO
Black  2010   SEL  15889    24920         AUTO
Black  2010    SE  15499     7784         AUTO
Black  2010    SE  15499    35636         AUTO
Black  2009    SE  14995    34419       MANUAL
Black  2011    SE  14992     4867         AUTO
Black  2011   SEL  14992    18948         AUTO
Black  2010   SEL  14990    33036         AUTO
Black  2010   SES  14761    44813         AUTO
Black  2010   SES  14677    22143       MANUAL
Black  2010    SE  14495    38275         AUTO
Black  2010    SE  14299    36447         AUTO
Black  2010   SES  14275    35318         AUTO
Black  2010    SE  13997    15167       MANUAL
Black  2010    SE  13995    20278       MANUAL
Black  2009   SES  13995    46126         AUTO
Black  2009   SES  13992    26887         AUTO
Black  2009    SE  13950     9450         AUTO
Black  2010    SE  13950    31414         AUTO
Black  2009   SES  13799    34888         AUTO
Black  2009   SES  13742    38380         AUTO
Black  2009   SES  13425    64055         AUTO
Black  2010    SE  13383    34503         AUTO
Black  2010    SE  12995    21325         AUTO
Black  2010    SE  12995    32743       MANUAL
Black  2010    SE  12780    35871         AUTO
Black  2008    SE  12777    49787       MANUAL
Black  2009    SE  11992    32559       MANUAL
Black  2009   SES  11984    59048         AUTO
Black  2008    SE  11754    38286         AUTO
Black  2010    SE  10717    64199         AUTO
Black  2007   SES   9999    78948       MANUAL
Black  2008    SE   8495   106171         AUTO
Black  2006   SES   7995    35000       MANUAL
Black  2004   SES   6950   119720         AUTO

In [66]:
wisc = pd.read_csv('c:/data/wisc_bc_data.csv',index_col="id")
wisc.shape

(569, 31)

In [67]:
wisc.head(10)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
id,,,,,,,,,,,,,,,,,,,,,
842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678
843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440
844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,0.1794,...,22.88,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368
84458202,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,...,17.06,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510
844981,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,0.2350,...,15.49,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720
84501001,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,0.2030,...,15.09,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750

In [69]:
wisc.iloc[842302:844359]

Empty DataFrame
Columns: [diagnosis, radius_mean, texture_mean, perimeter_mean, area_mean, smoothness_mean, compactness_mean, concavity_mean, concave points_mean, symmetry_mean, fractal_dimension_mean, radius_se, texture_se, perimeter_se, area_se, smoothness_se, compactness_se, concavity_se, concave points_se, symmetry_se, fractal_dimension_se, radius_worst, texture_worst, perimeter_worst, area_worst, smoothness_worst, compactness_worst, concavity_worst, concave points_worst, symmetry_worst, fractal_dimension_worst]
Index: []

[0 rows x 31 columns]

In [70]:
wisc.loc[842302:844359]

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
id,,,,,,,,,,,,,,,,,,,,,
842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678
843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.1578,0.08089,0.2087,...,15.47,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440
844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.1127,0.07400,0.1794,...,22.88,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368