In [1]:
import pandas as pd

In [2]:
cars = pd.read_csv('c:/data/usedcars.csv')
cars.head()

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  19995     7351  Silver         AUTO
3  2011   SEL  17809    11613    Gray         AUTO
4  2012    SE  17500     8367   White         AUTO

In [4]:
cars.model.value_counts()

model
SE     78
SES    48
SEL    24
Name: count, dtype: int64

In [13]:
cars.color.value_counts(normalize=True)

color
Black     0.233333
Silver    0.213333
Red       0.166667
Blue      0.113333
Gray      0.106667
White     0.106667
Green     0.033333
Yellow    0.020000
Gold      0.006667
Name: proportion, dtype: float64

In [14]:
cars.transmission.value_counts(normalize=True)

transmission
AUTO      0.853333
MANUAL    0.146667
Name: proportion, dtype: float64

In [7]:
cars.year.value_counts()

year
2010    49
2009    42
2011    16
2008    14
2007    11
2006     6
2004     3
2000     3
2005     2
2012     1
2003     1
2002     1
2001     1
Name: count, dtype: int64

In [20]:
cars.mileage.value_counts(normalize=True)

mileage
7413      0.006667
35871     0.006667
36323     0.006667
39211     0.006667
44789     0.006667
            ...
36447     0.006667
35318     0.006667
24929     0.006667
23785     0.006667
109259    0.006667
Name: proportion, Length: 150, dtype: float64

In [19]:
cars.model.value_counts(normalize=True,sort=True,ascending=True)

model
SEL    0.16
SES    0.32
SE     0.52
Name: proportion, dtype: float64

In [21]:
credit = pd.read_csv('c:/data/credit.csv')
credit.head()

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_length,installment_rate,personal_status,other_debtors,...,property,age,installment_plan,housing,existing_credits,default,dependents,telephone,foreign_worker,job
0,< 0 DM,6,critical,radio/tv,1169,unknown,> 7 yrs,4,single male,none,...,real estate,67,none,own,2,1,1,yes,yes,skilled employee
1,1 - 200 DM,48,repaid,radio/tv,5951,< 100 DM,1 - 4 yrs,2,female,none,...,real estate,22,none,own,1,2,1,none,yes,skilled employee
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 yrs,2,single male,none,...,real estate,49,none,own,1,1,2,none,yes,unskilled resident
3,< 0 DM,42,repaid,furniture,7882,< 100 DM,4 - 7 yrs,2,single male,guarantor,...,building society savings,45,none,for free,1,1,2,none,yes,skilled employee
4,< 0 DM,24,delayed,car (new),4870,< 100 DM,1 - 4 yrs,3,single male,none,...,unknown/none,53,none,for free,2,2,2,none,yes,skilled employee

In [22]:
credit['personal_status'].value_counts()

personal_status
single male      548
female           310
married male      92
divorced male     50
Name: count, dtype: int64

In [24]:
credit[['purpose']].value_counts()

purpose
radio/tv               280
car (new)              234
furniture              181
car (used)             103
business                97
education               50
repairs                 22
domestic appliances     12
others                  12
retraining               9
Name: count, dtype: int64

In [26]:
credit.personal_status[credit.purpose=='education'].value_counts()

personal_status
single male      27
female           21
divorced male     1
married male      1
Name: count, dtype: int64

In [28]:
credit.purpose[credit.personal_status=='female'].value_counts()

purpose
radio/tv               85
furniture              74
car (new)              70
car (used)             24
education              21
business               19
domestic appliances     6
repairs                 5
others                  3
retraining              3
Name: count, dtype: int64

In [29]:
credit.purpose[credit.personal_status=='single male'].value_counts()

purpose
radio/tv               146
car (new)              134
furniture               85
car (used)              70
business                59
education               27
repairs                 12
others                   8
domestic appliances      4
retraining               3
Name: count, dtype: int64

In [31]:
credit[credit.age>=50].purpose.value_counts()

purpose
radio/tv               33
car (new)              30
car (used)             15
furniture              13
business               12
education              12
repairs                 5
others                  3
domestic appliances     2
Name: count, dtype: int64

In [34]:
credit[credit.age<25].purpose.value_counts()

purpose
radio/tv               45
furniture              42
car (new)              25
car (used)             14
business                7
education               6
repairs                 5
domestic appliances     4
retraining              1
Name: count, dtype: int64

In [36]:
cars[cars.model=='SE'].color.value_counts()

color
Black     19
White     14
Red       12
Silver    11
Blue       9
Gray       7
Green      4
Gold       1
Yellow     1
Name: count, dtype: int64

In [37]:
cars[cars.model=='SES'].color.value_counts()

color
Silver    14
Black     12
Red       11
Blue       5
Gray       4
Yellow     1
White      1
Name: count, dtype: int64

In [39]:
cars[cars.model=='SEL'].color.value_counts()

color
Silver    7
Gray      5
Black     4
Blue      3
Red       2
Yellow    1
Green     1
White     1
Name: count, dtype: int64

In [48]:
cars[cars.year==2009].color.value_counts()

color
Black     9
Red       9
Blue      7
Silver    7
Gray      6
White     3
Gold      1
Name: count, dtype: int64

In [50]:
insurance = pd.read_csv('c:/data/insurance.csv')
insurance.head()

   age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [54]:
insurance.gender.value_counts(normalize=True).to_frame().reset_index()

   gender  proportion
0    male     0.50299
1  female     0.49701